log:
  level: trace

streams:
  webcam:
    exec:rpicam-vid --camera 0 --width 1280 --height 720 --framerate 15 -n -t 0 --codec mjpeg -o -

webrtc:
  listen: ":8555"

api:
  origin: "*"
  listen: ":1984"
