[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/pi/printer_data/comms/klippy.sock

[authorization]
trusted_clients:
    192.168.1.0/24
    10.20.30.1/32
    127.0.0.1/32
cors_domains:
    192.168.1.0/24
    *.lan
    *.local
    *://localhost
    *://localhost:*
    *://my.mainsail.xyz
    *://app.fluidd.xyz
    https://mainsail.fagmob.lol

[octoprint_compat]

[history]

[include klipper_timelapse.cfg]

[include klipper_estimator.cfg]

[update_manager]
channel: dev
refresh_interval: 168

[update_manager cartographer]
type: python
channel: stable
virtualenv: ~/klippy-env
project_name: cartographer3d-plugin
is_system_service: False
managed_services: klipper
info_tags: desc=Cartographer

[update_manager klipper-macros]
type: git_repo
origin: https://github.com/mattmerritt215/klipper-macros.git
path: ~/printer_data/config/klipper-macros
primary_branch: main
is_system_service: False
managed_services: klipper

[update_manager led_effect]
type: git_repo
path: ~/klipper-led_effect
origin: https://github.com/julianschill/klipper-led_effect.git
is_system_service: False

[update_manager mainsail]
path: /home/pi/mainsail
repo: mainsail-crew/mainsail
channel: stable
type: web
persistent_files:
    config.json

[update_manager mainsail-config]
managed_services: klipper
origin: https://github.com/mainsail-crew/mainsail-config.git
path: /home/pi/mainsail-config
primary_branch: master
type: git_repo

[update_manager crowsnest]
type: git_repo
path: ~/crowsnest
origin: https://github.com/mainsail-crew/crowsnest.git
primary_branch: v5
managed_services: crowsnest
system_dependencies: system-dependencies.json
virtualenv: ~/crowsnest-env
requirements: requirements.txt

[update_manager timelapse]
type: git_repo
primary_branch: main
path: ~/moonraker-timelapse
origin: https://github.com/mainsail-crew/moonraker-timelapse.git
managed_services: klipper moonraker

[include octoeverywhere-system.cfg]

[update_manager mobileraker]
install_script: /home/pi/mobileraker_companion/scripts/install.sh
requirements: /home/pi/mobileraker_companion/scripts/mobileraker-requirements.txt
env: /home/pi/mobileraker-env/bin/python
managed_services: mobileraker
primary_branch: main
origin: https://github.com/Clon1998/mobileraker_companion.git
path: /home/pi/mobileraker_companion
type: git_repo
